---
docker:
  image: "g4s8/gorultor:latest"
env:
  PATH: /usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  CGO_ENABLED: 0
merge:
  script:
    - "mkdir -pv /home/r/go/src/github.com/g4s8"
    - "ln -snv $PWD /home/r/go/src/github.com/g4s8/local-cdn"
    - "go get github.com/bclicn/color"
    - "go get github.com/elazarl/goproxy"
    - "go build -o /dev/null ."
  fast-forward: "no"
release:
  script: |-
    [[ "${tag}" =~ ^[0-9]+(\.[0-9]+)*$ ]] || exit -1
architect:
  - "g4s8"
