language: go
go:
  - 1.10.x
  - 1.11.x
before_install:
  - go get -v golang.org/x/lint/golint
  - go get -v "github.com/bclicn/color"
  - go get -v "github.com/elazarl/goproxy"
script:
  - go build -o /dev/null .
deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux
      condition: $TRAVIS_GO_VERSION = 1.11.x
